[package]
name = "euler-trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.1.26"
dashmap = "5.4.0"
inventory = "0.3.2"
once_cell = "1.16.0"
